[[FFLAS_FFPACK]]
arch = "aarch64"
git-tree-sha1 = "1805f169507362c3857c4ae3de86eb4b25cc4d66"
os = "macos"

    [[FFLAS_FFPACK.download]]
    sha256 = "125b7efc9d40addfc80acbf8e0a53a2c80c0bb8f410090e52a9b6a66befe3e44"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+2/FFLAS_FFPACK.v2.5.0.aarch64-apple-darwin.tar.gz"
[[FFLAS_FFPACK]]
arch = "aarch64"
git-tree-sha1 = "9d06cd349ea03cc905ba4f4f7f9e03e8feeed6a0"
libc = "glibc"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "e26301b2b843cb1dc20b6c4914c69fe19037c1be5e475338e284ae5fd3aa0a18"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+2/FFLAS_FFPACK.v2.5.0.aarch64-linux-gnu.tar.gz"
[[FFLAS_FFPACK]]
arch = "aarch64"
git-tree-sha1 = "cf8d953cc050efc6cb2c1160db6b42c1a24dc1ce"
libc = "musl"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "1fec9a2bbe9312136eb622306092ff3ad46690797cbced6a6a58d231f82ee3e4"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+2/FFLAS_FFPACK.v2.5.0.aarch64-linux-musl.tar.gz"
[[FFLAS_FFPACK]]
arch = "aarch64"
git-tree-sha1 = "9d06cd349ea03cc905ba4f4f7f9e03e8feeed6a0"
os = "freebsd"

    [[FFLAS_FFPACK.download]]
    sha256 = "e26301b2b843cb1dc20b6c4914c69fe19037c1be5e475338e284ae5fd3aa0a18"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+2/FFLAS_FFPACK.v2.5.0.aarch64-unknown-freebsd.tar.gz"
[[FFLAS_FFPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b8b9a8bcb0539a4adbaf7c47734f9f36c7f17680"
libc = "glibc"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "3a1eb8447ae21d5ac04a8eac19863cbac9c4b695f37567087b28f770196f9c8a"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+2/FFLAS_FFPACK.v2.5.0.armv6l-linux-gnueabihf.tar.gz"
[[FFLAS_FFPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9e9f082f4d7549045a7900a5bb66086d88d06b07"
libc = "musl"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "05ef8fccada42131f0a6717a14d38c043ce61d30d3f904fca683a044338b6241"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+2/FFLAS_FFPACK.v2.5.0.armv6l-linux-musleabihf.tar.gz"
[[FFLAS_FFPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b8b9a8bcb0539a4adbaf7c47734f9f36c7f17680"
libc = "glibc"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "3a1eb8447ae21d5ac04a8eac19863cbac9c4b695f37567087b28f770196f9c8a"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+2/FFLAS_FFPACK.v2.5.0.armv7l-linux-gnueabihf.tar.gz"
[[FFLAS_FFPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9e9f082f4d7549045a7900a5bb66086d88d06b07"
libc = "musl"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "05ef8fccada42131f0a6717a14d38c043ce61d30d3f904fca683a044338b6241"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+2/FFLAS_FFPACK.v2.5.0.armv7l-linux-musleabihf.tar.gz"
[[FFLAS_FFPACK]]
arch = "i686"
git-tree-sha1 = "b8b9a8bcb0539a4adbaf7c47734f9f36c7f17680"
libc = "glibc"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "3a1eb8447ae21d5ac04a8eac19863cbac9c4b695f37567087b28f770196f9c8a"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+2/FFLAS_FFPACK.v2.5.0.i686-linux-gnu.tar.gz"
[[FFLAS_FFPACK]]
arch = "i686"
git-tree-sha1 = "9e9f082f4d7549045a7900a5bb66086d88d06b07"
libc = "musl"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "05ef8fccada42131f0a6717a14d38c043ce61d30d3f904fca683a044338b6241"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+2/FFLAS_FFPACK.v2.5.0.i686-linux-musl.tar.gz"
[[FFLAS_FFPACK]]
arch = "powerpc64le"
git-tree-sha1 = "9d06cd349ea03cc905ba4f4f7f9e03e8feeed6a0"
libc = "glibc"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "e26301b2b843cb1dc20b6c4914c69fe19037c1be5e475338e284ae5fd3aa0a18"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+2/FFLAS_FFPACK.v2.5.0.powerpc64le-linux-gnu.tar.gz"
[[FFLAS_FFPACK]]
arch = "x86_64"
git-tree-sha1 = "1805f169507362c3857c4ae3de86eb4b25cc4d66"
os = "macos"

    [[FFLAS_FFPACK.download]]
    sha256 = "125b7efc9d40addfc80acbf8e0a53a2c80c0bb8f410090e52a9b6a66befe3e44"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+2/FFLAS_FFPACK.v2.5.0.x86_64-apple-darwin.tar.gz"
[[FFLAS_FFPACK]]
arch = "x86_64"
git-tree-sha1 = "9d06cd349ea03cc905ba4f4f7f9e03e8feeed6a0"
libc = "glibc"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "e26301b2b843cb1dc20b6c4914c69fe19037c1be5e475338e284ae5fd3aa0a18"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+2/FFLAS_FFPACK.v2.5.0.x86_64-linux-gnu.tar.gz"
[[FFLAS_FFPACK]]
arch = "x86_64"
git-tree-sha1 = "cf8d953cc050efc6cb2c1160db6b42c1a24dc1ce"
libc = "musl"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "1fec9a2bbe9312136eb622306092ff3ad46690797cbced6a6a58d231f82ee3e4"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+2/FFLAS_FFPACK.v2.5.0.x86_64-linux-musl.tar.gz"
[[FFLAS_FFPACK]]
arch = "x86_64"
git-tree-sha1 = "9d06cd349ea03cc905ba4f4f7f9e03e8feeed6a0"
os = "freebsd"

    [[FFLAS_FFPACK.download]]
    sha256 = "e26301b2b843cb1dc20b6c4914c69fe19037c1be5e475338e284ae5fd3aa0a18"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+2/FFLAS_FFPACK.v2.5.0.x86_64-unknown-freebsd.tar.gz"
