[[FFLAS_FFPACK]]
arch = "aarch64"
git-tree-sha1 = "79de6d65262015ef3c77dbda9972a6fe141e4a44"
os = "macos"

    [[FFLAS_FFPACK.download]]
    sha256 = "10009a3ac7c45b1e8eb995ec42ddfef04cb0c13b6785de4d80886e5fc6d49dc7"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+1/FFLAS_FFPACK.v2.5.0.aarch64-apple-darwin.tar.gz"
[[FFLAS_FFPACK]]
arch = "aarch64"
git-tree-sha1 = "d41aada91bc5d1a53c0b3eb432951af7f99a8816"
libc = "glibc"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "275b0cdfbb0b35d265d48410c3ad675943464f9cbd8efd4857690e6fcd11c294"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+1/FFLAS_FFPACK.v2.5.0.aarch64-linux-gnu.tar.gz"
[[FFLAS_FFPACK]]
arch = "aarch64"
git-tree-sha1 = "ffaeb975cae8d0f274d550619fdcdc1a2bacdc29"
libc = "musl"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "4e897f898cc70c152cfd1a4bdf682d5b7eecfa698ac908ad8992784d854fcdf3"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+1/FFLAS_FFPACK.v2.5.0.aarch64-linux-musl.tar.gz"
[[FFLAS_FFPACK]]
arch = "aarch64"
git-tree-sha1 = "d41aada91bc5d1a53c0b3eb432951af7f99a8816"
os = "freebsd"

    [[FFLAS_FFPACK.download]]
    sha256 = "275b0cdfbb0b35d265d48410c3ad675943464f9cbd8efd4857690e6fcd11c294"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+1/FFLAS_FFPACK.v2.5.0.aarch64-unknown-freebsd.tar.gz"
[[FFLAS_FFPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "83b14d2b0abf04161067d158146d61ed50e029cc"
libc = "glibc"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "ef5831f18c10edeaf486299bb6f67d3ed90869d3827f04739a023df0daf6739c"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+1/FFLAS_FFPACK.v2.5.0.armv6l-linux-gnueabihf.tar.gz"
[[FFLAS_FFPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cee4fa1e0c634c9297371d53f8f808c7ef5048c1"
libc = "musl"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "593e104b5177dc0bb71919f90b7a199422f8e7daf47a7564695c2256ac969b4c"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+1/FFLAS_FFPACK.v2.5.0.armv6l-linux-musleabihf.tar.gz"
[[FFLAS_FFPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "83b14d2b0abf04161067d158146d61ed50e029cc"
libc = "glibc"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "ef5831f18c10edeaf486299bb6f67d3ed90869d3827f04739a023df0daf6739c"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+1/FFLAS_FFPACK.v2.5.0.armv7l-linux-gnueabihf.tar.gz"
[[FFLAS_FFPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cee4fa1e0c634c9297371d53f8f808c7ef5048c1"
libc = "musl"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "593e104b5177dc0bb71919f90b7a199422f8e7daf47a7564695c2256ac969b4c"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+1/FFLAS_FFPACK.v2.5.0.armv7l-linux-musleabihf.tar.gz"
[[FFLAS_FFPACK]]
arch = "i686"
git-tree-sha1 = "83b14d2b0abf04161067d158146d61ed50e029cc"
libc = "glibc"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "ef5831f18c10edeaf486299bb6f67d3ed90869d3827f04739a023df0daf6739c"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+1/FFLAS_FFPACK.v2.5.0.i686-linux-gnu.tar.gz"
[[FFLAS_FFPACK]]
arch = "i686"
git-tree-sha1 = "cee4fa1e0c634c9297371d53f8f808c7ef5048c1"
libc = "musl"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "593e104b5177dc0bb71919f90b7a199422f8e7daf47a7564695c2256ac969b4c"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+1/FFLAS_FFPACK.v2.5.0.i686-linux-musl.tar.gz"
[[FFLAS_FFPACK]]
arch = "powerpc64le"
git-tree-sha1 = "d41aada91bc5d1a53c0b3eb432951af7f99a8816"
libc = "glibc"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "275b0cdfbb0b35d265d48410c3ad675943464f9cbd8efd4857690e6fcd11c294"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+1/FFLAS_FFPACK.v2.5.0.powerpc64le-linux-gnu.tar.gz"
[[FFLAS_FFPACK]]
arch = "x86_64"
git-tree-sha1 = "79de6d65262015ef3c77dbda9972a6fe141e4a44"
os = "macos"

    [[FFLAS_FFPACK.download]]
    sha256 = "10009a3ac7c45b1e8eb995ec42ddfef04cb0c13b6785de4d80886e5fc6d49dc7"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+1/FFLAS_FFPACK.v2.5.0.x86_64-apple-darwin.tar.gz"
[[FFLAS_FFPACK]]
arch = "x86_64"
git-tree-sha1 = "d41aada91bc5d1a53c0b3eb432951af7f99a8816"
libc = "glibc"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "275b0cdfbb0b35d265d48410c3ad675943464f9cbd8efd4857690e6fcd11c294"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+1/FFLAS_FFPACK.v2.5.0.x86_64-linux-gnu.tar.gz"
[[FFLAS_FFPACK]]
arch = "x86_64"
git-tree-sha1 = "ffaeb975cae8d0f274d550619fdcdc1a2bacdc29"
libc = "musl"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "4e897f898cc70c152cfd1a4bdf682d5b7eecfa698ac908ad8992784d854fcdf3"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+1/FFLAS_FFPACK.v2.5.0.x86_64-linux-musl.tar.gz"
[[FFLAS_FFPACK]]
arch = "x86_64"
git-tree-sha1 = "d41aada91bc5d1a53c0b3eb432951af7f99a8816"
os = "freebsd"

    [[FFLAS_FFPACK.download]]
    sha256 = "275b0cdfbb0b35d265d48410c3ad675943464f9cbd8efd4857690e6fcd11c294"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+1/FFLAS_FFPACK.v2.5.0.x86_64-unknown-freebsd.tar.gz"
