[[FFLAS_FFPACK]]
arch = "aarch64"
git-tree-sha1 = "6ea436fab2981cd83e26b5f7f0fc56060fe911ce"
os = "macos"

    [[FFLAS_FFPACK.download]]
    sha256 = "a5b94c100720cfd6c50d076a26f8cae9c7b78529b7980f80794259ffdd6bfac9"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+0/FFLAS_FFPACK.v2.5.0.aarch64-apple-darwin.tar.gz"
[[FFLAS_FFPACK]]
arch = "aarch64"
git-tree-sha1 = "1d532d886ad768792c4be91a0a4a04bb8842ee7c"
libc = "glibc"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "4bdb703fb5d4009d1a6f88e5de08a473d22327ede9e46bda45977fafc890ff00"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+0/FFLAS_FFPACK.v2.5.0.aarch64-linux-gnu.tar.gz"
[[FFLAS_FFPACK]]
arch = "aarch64"
git-tree-sha1 = "17e200db889657c6cb5e56de73032ebc1f91184f"
libc = "musl"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "b905f4ab4bd263c6bfc9dc7b3774d55df8243a94e586f57bc279d850d03457c4"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+0/FFLAS_FFPACK.v2.5.0.aarch64-linux-musl.tar.gz"
[[FFLAS_FFPACK]]
arch = "aarch64"
git-tree-sha1 = "1d532d886ad768792c4be91a0a4a04bb8842ee7c"
os = "freebsd"

    [[FFLAS_FFPACK.download]]
    sha256 = "4bdb703fb5d4009d1a6f88e5de08a473d22327ede9e46bda45977fafc890ff00"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+0/FFLAS_FFPACK.v2.5.0.aarch64-unknown-freebsd.tar.gz"
[[FFLAS_FFPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c3cb4ec1e0fe3bd4e807f8346b68e4fb9c719ae8"
libc = "glibc"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "f9cff9954c4c8c37cdac46ede09db0ff774503d9d3b557b8dc88510904821f54"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+0/FFLAS_FFPACK.v2.5.0.armv6l-linux-gnueabihf.tar.gz"
[[FFLAS_FFPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2e91bf5ebbd0ed2eb45d4b7e24c532a90e1a9ad2"
libc = "musl"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "7729738b37fc8fc1ab2f377a620414c87af6ecf307116cdad00fc9de9bd32f14"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+0/FFLAS_FFPACK.v2.5.0.armv6l-linux-musleabihf.tar.gz"
[[FFLAS_FFPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c3cb4ec1e0fe3bd4e807f8346b68e4fb9c719ae8"
libc = "glibc"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "f9cff9954c4c8c37cdac46ede09db0ff774503d9d3b557b8dc88510904821f54"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+0/FFLAS_FFPACK.v2.5.0.armv7l-linux-gnueabihf.tar.gz"
[[FFLAS_FFPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2e91bf5ebbd0ed2eb45d4b7e24c532a90e1a9ad2"
libc = "musl"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "7729738b37fc8fc1ab2f377a620414c87af6ecf307116cdad00fc9de9bd32f14"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+0/FFLAS_FFPACK.v2.5.0.armv7l-linux-musleabihf.tar.gz"
[[FFLAS_FFPACK]]
arch = "i686"
git-tree-sha1 = "c3cb4ec1e0fe3bd4e807f8346b68e4fb9c719ae8"
libc = "glibc"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "f9cff9954c4c8c37cdac46ede09db0ff774503d9d3b557b8dc88510904821f54"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+0/FFLAS_FFPACK.v2.5.0.i686-linux-gnu.tar.gz"
[[FFLAS_FFPACK]]
arch = "i686"
git-tree-sha1 = "2e91bf5ebbd0ed2eb45d4b7e24c532a90e1a9ad2"
libc = "musl"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "7729738b37fc8fc1ab2f377a620414c87af6ecf307116cdad00fc9de9bd32f14"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+0/FFLAS_FFPACK.v2.5.0.i686-linux-musl.tar.gz"
[[FFLAS_FFPACK]]
arch = "powerpc64le"
git-tree-sha1 = "1d532d886ad768792c4be91a0a4a04bb8842ee7c"
libc = "glibc"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "4bdb703fb5d4009d1a6f88e5de08a473d22327ede9e46bda45977fafc890ff00"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+0/FFLAS_FFPACK.v2.5.0.powerpc64le-linux-gnu.tar.gz"
[[FFLAS_FFPACK]]
arch = "x86_64"
git-tree-sha1 = "6ea436fab2981cd83e26b5f7f0fc56060fe911ce"
os = "macos"

    [[FFLAS_FFPACK.download]]
    sha256 = "a5b94c100720cfd6c50d076a26f8cae9c7b78529b7980f80794259ffdd6bfac9"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+0/FFLAS_FFPACK.v2.5.0.x86_64-apple-darwin.tar.gz"
[[FFLAS_FFPACK]]
arch = "x86_64"
git-tree-sha1 = "1d532d886ad768792c4be91a0a4a04bb8842ee7c"
libc = "glibc"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "4bdb703fb5d4009d1a6f88e5de08a473d22327ede9e46bda45977fafc890ff00"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+0/FFLAS_FFPACK.v2.5.0.x86_64-linux-gnu.tar.gz"
[[FFLAS_FFPACK]]
arch = "x86_64"
git-tree-sha1 = "17e200db889657c6cb5e56de73032ebc1f91184f"
libc = "musl"
os = "linux"

    [[FFLAS_FFPACK.download]]
    sha256 = "b905f4ab4bd263c6bfc9dc7b3774d55df8243a94e586f57bc279d850d03457c4"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+0/FFLAS_FFPACK.v2.5.0.x86_64-linux-musl.tar.gz"
[[FFLAS_FFPACK]]
arch = "x86_64"
git-tree-sha1 = "1d532d886ad768792c4be91a0a4a04bb8842ee7c"
os = "freebsd"

    [[FFLAS_FFPACK.download]]
    sha256 = "4bdb703fb5d4009d1a6f88e5de08a473d22327ede9e46bda45977fafc890ff00"
    url = "https://github.com/JuliaBinaryWrappers/FFLAS_FFPACK_jll.jl/releases/download/FFLAS_FFPACK-v2.5.0+0/FFLAS_FFPACK.v2.5.0.x86_64-unknown-freebsd.tar.gz"
